server:
  port: 8247

weekend:
  mongodb:
    uri: jdbc:mongodb://148.70.16.82:27017/weekend-dev
    driver-name: com.github.aly8246.core.driver.MongoDriver
  config:
    non-field-remind: true
    show-param: true
    show-command: true
    show-condition: true
    show-result: true
