server:
  port: 8247

spring:
  data:
    mongodb:
      uri: mongodb://148.70.16.82:27017/weekend-dev
weekend:
  mongodb:
    uri: jdbc:mongodb://148.70.16.82:27017/weekend-dev
    driver-name: com.github.aly8246.core.driver.MongoDriver
